# Generated by Django 5.2.3 on 2025-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('for_parts', 'For Parts')], default='used', max_length=20),
        ),
    ]
